/*SELECT * FROM CODIGOS_RESET_PASSWORD ORDER BY creado_en DESC;
 
 
 CREATE TABLE CODIGOS_RESET_PASSWORD (
 id          SERIAL PRIMARY KEY,
 email       VARCHAR(255) NOT NULL,
 codigo      VARCHAR(6)   NOT NULL,
 expira_en   TIMESTAMP    NOT NULL,
 usado       BOOLEAN      DEFAULT FALSE,
 creado_en   TIMESTAMP    DEFAULT NOW()
 );
 
 CREATE INDEX idx_reset_email ON CODIGOS_RESET_PASSWORD (email, usado); */